[package]
name = "ksbot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-util = { version = "0.3", features = ["sink", "std"] }
serde_json = "1.0.83"
tini = "1.3.0"
serde = { version = "1", features = ["derive"] }
anyhow = "1.0.61"
reqwest = { version = "0.11.11", features = ["json"] }
lazy_static = "1.4.0"
tokio-tungstenite = "0.17.2"
tokio = { version = "1", features = ["full"] }
url = "2.0.0"
