name: Publish Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create-release.outputs.upload_url }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 256
    - name: Fetch all tags
      run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - name: Generate Changelog
      id: changelog
      run: |
        prev_tag=$(git describe --abbrev=0 --tags ${{ github.ref }}^)
        log=$(git log --oneline --decorate=no $prev_tag..${{ github.ref }})
        log="${log//'%'/'%25'}"
        log="${log//$'\n'/'%0A'}"
        log="${log//$'\r'/'%0D'}"
        echo "::set-output name=value::$log"
    - name: Create Release
      id: create-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: ${{ steps.changelog.outputs.value }}
        draft: false
        prerelease: false
